"""
Predictive ML Streamlit App generated by RAD-ML.
Calls a SageMaker endpoint to return predictions.
"""
import os
import sys
from pathlib import Path
import streamlit as st
import pandas as pd
import json

try:
    import boto3
except ImportError:
    boto3 = None

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))
os.chdir(ROOT)

import yaml
with open(ROOT / "config.yaml", encoding="utf-8") as f:
    CFG = yaml.safe_load(f)

# Page Config
st.set_page_config(page_title="ML Prediction App", layout="wide")

# Custom CSS
st.markdown("""
<style>
    .stApp { background-color: #0e1117; }
    .prediction-box {
        padding: 2rem; border-radius: 1rem; text-align: center;
        background: linear-gradient(145deg, rgba(59, 130, 246, 0.2), rgba(16, 185, 129, 0.2));
        border: 2px solid rgba(255, 255, 255, 0.1);
        box-shadow: 0 0 20px rgba(59, 130, 246, 0.3);
        margin: 2rem 0;
    }
    .metrics-panel {
        background: rgba(255, 255, 255, 0.05); padding: 1rem; border-radius: 0.5rem;
    }
</style>
""", unsafe_allow_html=True)

# App Init
ENDPOINT_NAME = os.environ.get("SAGEMAKER_ENDPOINT", CFG.get("aws", {}).get("sagemaker_endpoint_name", "rad-ml-endpoint"))
AWS_REGION = CFG.get("aws", {}).get("region", "us-east-1")
FEATURES = list(CFG.get("ml_features", []))
if not FEATURES:
    FEATURES = ["region", "area", "bedrooms", "bathrooms", "age_of_property"]

METRICS = {
    "algorithm": "XGBoost",
    "metrics": { "mae": 0.0, "rmse": 0.0, "r2": 0.0 }
}

try:
    sm_runtime = boto3.client("sagemaker-runtime", region_name=AWS_REGION) if boto3 else None
except:
    sm_runtime = None

def _encode_feature(feature_name: str, value: str) -> str:
    value = str(value).strip()
    if feature_name == "region":
        return str(sum(ord(ch) for ch in value.lower()) % 1000)
    try:
        return str(float(value))
    except ValueError:
        return value

def make_prediction(values_list):
    payload = ",".join(values_list)
    if sm_runtime is None:
        # Fallback local dummy logic
        nums = [float(v) for v in values_list if v.replace('.','',1).isdigit()]
        return str(round(sum(nums) / max(len(nums), 1), 3))
    else:
        response = sm_runtime.invoke_endpoint(
            EndpointName=ENDPOINT_NAME,
            ContentType="text/csv",
            Body=payload,
        )
        return response["Body"].read().decode("utf-8").strip()

# UI Layout
st.title("🔮 Predictive ML Engine")

col1, col2 = st.columns([2, 1])

with col1:
    st.subheader("Input Features")
    form_data = {}
    
    # Generate dynamic inputs
    cols = st.columns(2)
    for i, feature in enumerate(FEATURES):
        with cols[i % 2]:
            form_data[feature] = st.text_input(f"{feature.title().replace('_', ' ')}", key=f"inp_{feature}")
    
    # Bulk predict
    uploaded_file = st.file_uploader("Or upload CSV for Bulk Predict", type=["csv"])
    
    if st.button("Predict 🚀", use_container_width=True):
        if uploaded_file is not None:
            st.info("Bulk predict logic would execute here.")
        else:
            missing = [f for f in FEATURES if not form_data[f].strip()]
            if missing:
                st.error(f"Missing required fields: {', '.join(missing)}")
            elif "region" in FEATURES and not form_data["region"].strip():
                st.error("Region is required for location-wise prediction.")
            else:
                with st.spinner("Invoking Model..."):
                    try:
                        encoded = [_encode_feature(f, form_data[f]) for f in FEATURES]
                        pred_val = make_prediction(encoded)
                        st.markdown(f'<div class="prediction-box"><h3>Prediction Result:</h3><h1>{pred_val}</h1></div>', unsafe_allow_html=True)
                    except Exception as e:
                        st.error(f"Prediction Error: {e}")

with col2:
    st.subheader("Model Information")
    st.markdown('<div class="metrics-panel">', unsafe_allow_html=True)
    st.markdown(f"**Algorithm:** {METRICS['algorithm']}")
    st.markdown("**Metrics:**")
    st.json(METRICS["metrics"])
    st.markdown("</div>", unsafe_allow_html=True)
