"""
generator/templates/base_flask.py
=================================
Offline fallback templates for generated applications.

These templates intentionally use Flask (not Streamlit) so the
pipeline can run in constrained environments where Streamlit is not
available.
"""

# ---------------------------------------------------------------------------
# CHATBOT - RAG + SLM Flask App
# ---------------------------------------------------------------------------
FLASK_APP_CHATBOT = '''"""
Chatbot Flask app generated by RAD-ML fallback.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Optional

from flask import Flask, jsonify, render_template_string, request

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))
os.chdir(ROOT)

import yaml

with open(ROOT / "config.yaml", encoding="utf-8") as f:
    CFG = yaml.safe_load(f)

app = Flask(__name__)
_RAG_INSTANCE = None


def get_rag():
    """Lazy load RAG builder so app import stays lightweight for tests."""
    global _RAG_INSTANCE
    if _RAG_INSTANCE is not None:
        return _RAG_INSTANCE

    try:
        from engines.chatbot_engine.rag_builder import RAGBuilder
        rag = RAGBuilder(CFG)
        if not rag.load_existing_index():
            return None
        _RAG_INSTANCE = rag
        return _RAG_INSTANCE
    except Exception:
        return None


@app.get("/")
def home():
    return render_template_string(
        """
        <html>
        <head><title>RAD-ML Chatbot</title></head>
        <body>
          <h2>RAD-ML Chatbot (Fallback Flask Mode)</h2>
          <form method="post" action="/api/chat">
            <input type="text" name="question" placeholder="Ask a question" style="width: 360px;" />
            <button type="submit">Ask</button>
          </form>
        </body>
        </html>
        """
    )


@app.post("/api/chat")
def chat():
    payload = request.get_json(silent=True) or {}
    question = str(payload.get("question") or request.form.get("question") or "").strip()
    if not question:
        return jsonify({"ok": False, "error": "Question is required."}), 400

    rag = get_rag()
    if rag is None:
        return jsonify({
            "ok": True,
            "answer": "RAG index is unavailable. Run chatbot collection/indexing first."
        })

    try:
        answer = str(rag.query(question)).strip()
        if not answer:
            answer = "No confident answer could be generated."
        return jsonify({"ok": True, "answer": answer})
    except Exception as exc:
        return jsonify({"ok": False, "error": str(exc)}), 500


if __name__ == "__main__":
    flask_cfg = CFG.get("flask", {})
    host = str(flask_cfg.get("host", "0.0.0.0"))
    port = int(flask_cfg.get("port", 5000))
    debug = bool(flask_cfg.get("debug", False))
    app.run(host=host, port=port, debug=debug)
'''

# ---------------------------------------------------------------------------
# ML - SageMaker Endpoint Flask App
# ---------------------------------------------------------------------------
FLASK_APP_ML = '''"""
Predictive ML Flask app generated by RAD-ML fallback.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

from flask import Flask, jsonify, render_template_string, request

try:
    import boto3
except Exception:
    boto3 = None

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))
os.chdir(ROOT)

import yaml

with open(ROOT / "config.yaml", encoding="utf-8") as f:
    CFG = yaml.safe_load(f)

app = Flask(__name__)

ENDPOINT_NAME = os.environ.get(
    "SAGEMAKER_ENDPOINT",
    CFG.get("aws", {}).get("sagemaker_endpoint_name", "rad-ml-endpoint"),
)
AWS_REGION = CFG.get("aws", {}).get("region", "us-east-1")
FEATURES = list(CFG.get("ml_features", [])) or [
    "region",
    "area",
    "bedrooms",
    "bathrooms",
    "age_of_property",
]

try:
    sm_runtime = boto3.client("sagemaker-runtime", region_name=AWS_REGION) if boto3 else None
except Exception:
    sm_runtime = None


def _encode_feature(feature_name: str, value: str) -> str:
    value = str(value).strip()
    if feature_name == "region":
        return str(sum(ord(ch) for ch in value.lower()) % 1000)
    try:
        return str(float(value))
    except ValueError:
        return value


def make_prediction(values_list):
    payload = ",".join(values_list)
    if sm_runtime is None:
        nums = [float(v) for v in values_list if str(v).replace(".", "", 1).isdigit()]
        return str(round(sum(nums) / max(len(nums), 1), 3))

    response = sm_runtime.invoke_endpoint(
        EndpointName=ENDPOINT_NAME,
        ContentType="text/csv",
        Body=payload,
    )
    return response["Body"].read().decode("utf-8").strip()


@app.get("/")
def home():
    fields_html = "".join(
        f'<label>{f}: <input name="{f}" /></label><br/>'
        for f in FEATURES
    )
    return render_template_string(
        f"""
        <html>
        <head><title>RAD-ML Prediction</title></head>
        <body>
          <h2>RAD-ML Prediction (Fallback Flask Mode)</h2>
          <form method="post" action="/predict">
            {fields_html}
            <button type="submit">Predict</button>
          </form>
        </body>
        </html>
        """
    )


@app.post("/predict")
def predict():
    payload = request.get_json(silent=True) or request.form.to_dict(flat=True) or {}
    missing = [f for f in FEATURES if not str(payload.get(f, "")).strip()]
    if missing:
        return jsonify({"ok": False, "error": f"Missing required fields: {', '.join(missing)}"}), 400

    if "region" in FEATURES and not str(payload.get("region", "")).strip():
        return jsonify({"ok": False, "error": "Region is required for location-wise prediction."}), 400

    try:
        encoded = [_encode_feature(f, payload.get(f, "")) for f in FEATURES]
        result = make_prediction(encoded)
        return jsonify({"ok": True, "prediction": result, "features": FEATURES})
    except Exception as exc:
        return jsonify({"ok": False, "error": str(exc)}), 500


if __name__ == "__main__":
    flask_cfg = CFG.get("flask", {})
    host = str(flask_cfg.get("host", "0.0.0.0"))
    port = int(flask_cfg.get("port", 5000))
    debug = bool(flask_cfg.get("debug", False))
    app.run(host=host, port=port, debug=debug)
'''
