"""
Predictive ML Streamlit app generated by RAD-ML fallback.
"""
from __future__ import annotations

import io
import os
import sys
from pathlib import Path
from typing import Dict, List, Tuple

import streamlit as st
import yaml

try:
    import boto3
except Exception:
    boto3 = None

try:
    import pandas as pd
except Exception:
    pd = None

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))
os.chdir(ROOT)

with open(ROOT / "config.yaml", encoding="utf-8") as f:
    CFG = yaml.safe_load(f)

ENDPOINT_NAME = os.environ.get(
    "SAGEMAKER_ENDPOINT",
    CFG.get("aws", {}).get("sagemaker_endpoint_name", "rad-ml-endpoint"),
)
AWS_REGION = CFG.get("aws", {}).get("region", "us-east-1")
FEATURES = list(CFG.get("ml_features", [])) or [
    "region",
    "area",
    "bedrooms",
    "bathrooms",
    "age_of_property",
]

try:
    sm_runtime = boto3.client("sagemaker-runtime", region_name=AWS_REGION) if boto3 else None
except Exception:
    sm_runtime = None


def _encode_feature(feature_name: str, value: str) -> str:
    value = str(value).strip()
    if feature_name == "region":
        return str(sum(ord(ch) for ch in value.lower()) % 1000)
    try:
        return str(float(value))
    except ValueError:
        return value


def _is_numeric(value: str) -> bool:
    try:
        float(str(value).strip())
        return True
    except Exception:
        return False


def validate_payload(payload: Dict[str, str]) -> Tuple[bool, str]:
    missing = [f for f in FEATURES if not str(payload.get(f, "")).strip()]
    if missing:
        return False, f"Missing required fields: {', '.join(missing)}"
    if "region" in FEATURES and not str(payload.get("region", "")).strip():
        return False, "Region is required for location-wise prediction."
    return True, ""


def make_prediction(values_list: List[str]) -> str:
    payload = ",".join(values_list)
    if sm_runtime is None:
        nums = [float(v) for v in values_list if _is_numeric(v)]
        return str(round(sum(nums) / max(len(nums), 1), 3))

    response = sm_runtime.invoke_endpoint(
        EndpointName=ENDPOINT_NAME,
        ContentType="text/csv",
        Body=payload,
    )
    return response["Body"].read().decode("utf-8").strip()


def predict_record(record: Dict[str, str]) -> str:
    encoded = [_encode_feature(f, record.get(f, "")) for f in FEATURES]
    return make_prediction(encoded)


def main():
    st.set_page_config(page_title="RAD-ML Predictor", layout="wide")
    st.title("RAD-ML Predictor")
    st.caption("Streamlit fallback mode for ML inference")

    with st.sidebar:
        st.markdown("### Deployment")
        st.write("Algorithm: XGBoost (SageMaker Built-in)")
        st.write(f"Endpoint: {ENDPOINT_NAME}")
        st.write(f"Region: {AWS_REGION}")

    tab_single, tab_bulk = st.tabs(["Single Predict", "Bulk Predict"])

    with tab_single:
        st.subheader("Single Prediction")
        cols = st.columns(2)
        inputs: Dict[str, str] = {}
        for idx, feat in enumerate(FEATURES):
            label = feat.replace("_", " ").title()
            with cols[idx % 2]:
                inputs[feat] = st.text_input(label, key=f"single_{feat}")

        if st.button("Predict", type="primary"):
            ok, error_msg = validate_payload(inputs)
            if not ok:
                st.error(error_msg)
            else:
                try:
                    with st.spinner("Running inference..."):
                        prediction = predict_record(inputs)
                    st.success(f"Prediction: {prediction}")
                except Exception as exc:
                    st.error(f"Inference failed: {exc}")

    with tab_bulk:
        st.subheader("Bulk Prediction")
        if pd is None:
            st.info("Install pandas to enable bulk prediction from CSV.")
        else:
            file = st.file_uploader("Upload CSV with required feature columns", type=["csv"])
            if file is not None:
                try:
                    df = pd.read_csv(file)
                except Exception as exc:
                    st.error(f"Failed to parse CSV: {exc}")
                    df = None

                if df is not None:
                    missing_cols = [f for f in FEATURES if f not in df.columns]
                    if missing_cols:
                        st.error(f"CSV missing required columns: {', '.join(missing_cols)}")
                    else:
                        st.dataframe(df.head(20), use_container_width=True)
                        if st.button("Run Bulk Prediction"):
                            try:
                                with st.spinner("Running bulk inference..."):
                                    predictions = []
                                    for _, row in df.iterrows():
                                        rec = {f: str(row.get(f, "")) for f in FEATURES}
                                        ok, error_msg = validate_payload(rec)
                                        if not ok:
                                            predictions.append(f"ERROR: {error_msg}")
                                            continue
                                        predictions.append(predict_record(rec))
                                out_df = df.copy()
                                out_df["prediction"] = predictions
                                st.dataframe(out_df, use_container_width=True)

                                csv_data = out_df.to_csv(index=False).encode("utf-8")
                                st.download_button(
                                    "Download Predictions CSV",
                                    data=csv_data,
                                    file_name="predictions.csv",
                                    mime="text/csv",
                                )
                            except Exception as exc:
                                st.error(f"Bulk inference failed: {exc}")


if __name__ == "__main__":
    main()
